cpu_monitor:
  description: >
    Based on this user query "{user_query}""
    Provide the CPU usage if requested by the user
    *Guidelines*:
    - If query mentions "CPU", "processor", "processing" → provide CPU usage
    - Do NOT run this task unless CPU is explicitly requested by the user.
  expected_output: >
    Convey the CPU percentage to the user and mentioned it is for all cores together, Your response should be in a conversational tone.
  agent: sysadmin_agent

memory_monitor:
  description: >
    Based on this user query "{user_query}"
    Provide the Memory Percentage if requested by the user
    *Guidelines*:
    - If query mentions "memory", "RAM" → provide memory usage
    - Do NOT run this task unless memory is explicilty requested by the user.
  expected_output:
    Convey the memory percentage to the user and mention it is only virtual memory, Your response should be in a conversational tone.
  agent: sysadmin_agent

battery_monitor:
  description: >
    Based on this user query "{user_query}"

    Provide the Battery Percentage if requested by the user
    *Guidelines*:
    - If query mentions "battery", "power", "charge" → provide battery status
    - Do NOT run this task unless battery is explicilty requested by the user.
  expected_output:
    Convey the battery percentage to the user, If the Tool returns -1 tell user that no battery information is available, Your response should be in a conversational tone.
  agent: sysadmin_agent

running_process:
  description: >
    Based on this user query: "{user_query}"
    
    Determine if the user wants process information:
    - If query mentions "processes", "tasks", "programs", "apps" → provide process list
    - If query mentions "top X" → provide X number of processes
    - If query mentions "all", "system stats" → provide top 3 processes
    - If no process-related keywords, do NOT provide process information and do not run this task.
    
    Extract the number of processes requested (default to 3 if not specified).
    DO NOT run this task unless process information is explicitly requested by the user.
  expected_output:
    Greet the user,
    Acknowledge them
    give them the Parent Process Name and Total CPU of the parent process 
    and then the Process_index, Process ID, Name of the Process and CPU Usage Percentage 
    of all the children in a Table format with tree like structure connecting the parent and the children.
  agent: sysadmin_agent
